import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>ShipGuessr</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script id="polyfill">
          {
            `
              if (!String.prototype.upperFirst)
                window.String.prototype.upperFirst = function () {
                  return this.charAt(0).toUpperCase() + this.slice(1);
                };
            `
          }
        </Script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
